### ISSUE TITLE
我复制、修改了代码

### ISSUE THREAD

**Issue by zombie110year** [qyxf/templates-of-LaTeX#4]
很喜欢你们编写的样式，我把它做成一个 git 仓库了，以便直接 clone 下来就用。
但为了让代码看起来干净一点，我对文件进行了一些修改，这似乎违反了 LPPL 协议，
所以想询问一下，你们是否允许这种行为？

谢谢！

仓库地址 https://github.com/zombie110year/qyxf-book-template

**Comment by xjtu-blacksmith** [comment]
您好！LPPL 协议正文有些冗长，一直没能很仔细的读完。就我对 LPPL 协议的理解，其是容许修改作品的，需要通过其设定的名为「Derived Work」的机制实现。这一部分在协议的「
CONDITIONS ON DISTRIBUTION AND MODIFICATION」下第 6 条，要求 Derived Work 应满足：

- 被修改的内容（文件）需在与 Base Interpreter（编译器）的交互过程（即通过终端输出信息）中**清楚地、不含混地**说明自己是在原作品基础上修改过的版本；
- 作品的所有内容中应标明相对于原作品修改的内容，用明确的日志给出；
- Derived Work 中不应给出任何信息，表明任何人（包括原作者）会对这份作品的可用性负责（负责改进模板中的错误等），给予支持；
- 需要在 Derived Work 中附加一份未经修改的、完整的原作品，或足够使其他人获取到原作品的信息（如链接等）。

其中的第一条，旧版本的说法是「必须用与原作品不同的名称」，现在有所弱化。

要求甚多，主要是因为这些内容是针对 LaTeX  内核、宏包、文档类等工具性质的作品而设定的，对像 qyxf-sets 这样的「模板」而言并不很方便。LPPL 的设计初衷似乎是保证作品能在不同的电脑上以相同的方式运行、编译，而不是便于作品的传播、演绎。

本份模板选用 LPPL 协议，原来也只是为了保护这份模板自身不被随意修改、传播。现在如您：

- 仅需要个人使用，可以存在个人目录（包括 GitHub 上的私有仓库）里任意修改（不需要关心许可协议，因为这样的作品并未被 distribute）；
- 需要发布在网上，原则上应把上面「繁琐」的步骤一一实现；不过，就我的理解，简单的做法是将项目和 `cls` 文件名换掉（尽管没有要求，但是确为惯例），再在 `cls` 文件或 README 等地方用几段话简单地说明一下改动、给出本项目链接（注意到您已经加上了）即可，这已与协议要求相符。

我也会根据这份模板之后的传播情况，考虑使用 LPPL 协议的合理性。

**Comment by zombie110year** [comment]
好的，谢谢你的解答。

**Comment by xjtu-blacksmith** [comment]
此坑已弃，新项目移到 `qyxf-book` 仓库下，地址为 <https://github.com/qyxf/qyxf-book>。现采用宽松的 MIT 许可证，可以放心使用。
